### ISSUE TITLE
the location of datasets

### ISSUE THREAD

**Issue by hust-wuhan** [deropty/LDS#1]
I'd like to ask which folder the dataset is placed under, and are there any requirements?

**Comment by deropty** [comment]
Please refer to [datasets](https://github.com/JDAI-CV/fast-reid/blob/39887a102eeec84661f0c0332000f8138aa9109d/datasets/README.md) and [requirements](https://github.com/JDAI-CV/fast-reid/blob/master/INSTALL.md).
